import type { Animal } from '../types';

export const MOCK_ANIMALS: Animal[] = [
  {
    id: '1',
    name: 'Luna',
    species: 'Perro',
    breed: 'Golden Retriever',
    age: '2 años',
    status: 'Disponible',
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=400',
    entryDate: '2024-02-15',
    hasChip: false,
    isSterilized: false,
    photos: [],
    medicalRecords: [],
  },
  {
    id: '2',
    name: 'Oliver',
    species: 'Gato',
    breed: 'Siamés',
    age: '5 meses',
    status: 'En Cuarentena',
    image: 'https://images.unsplash.com/photo-1513245543132-31f507417b26?auto=format&fit=crop&q=80&w=400',
    entryDate: '2024-03-01',
    hasChip: false,
    isSterilized: false,
    photos: [],
    medicalRecords: [],
  },
  {
    id: '3',
    name: 'Max',
    species: 'Perro',
    breed: 'Labrador',
    age: '4 años',
    status: 'Médico',
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=400',
    entryDate: '2024-01-20',
    hasChip: true,
    isSterilized: false,
    photos: [],
    medicalRecords: [],
  },
  {
    id: '4',
    name: 'Bella',
    species: 'Gato',
    breed: 'Mestizo',
    age: '1 año',
    status: 'Adoptado',
    image: 'https://images.unsplash.com/photo-1533733509137-8f6f9889a80b?auto=format&fit=crop&q=80&w=400',
    entryDate: '2023-11-10',
    hasChip: false,
    isSterilized: true,
    photos: [],
    medicalRecords: [],
  },
];
